#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1390015257                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/us/app/my-prayers/id1390015257                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.kosratdahmad.myprayers&hl=en                                          # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.webp                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : +1 Million Downloads                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : My Prayers is an Islamic app that offers accurate prayer times, Qibla direction, Azkars (Hisnul Muslim), 99 Names of Allah, and more.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Kosrat D. Ahmed                                
your_link                                 : https://kosrat.dev                     
your_city                                 :                                 
email_address                             : contact@myprayers.io
linkedin_username                         :                                           
linkedin_company                          : my-prayers                                          
facebook_username                         : my.prayers.times                                          
instagram_username                        : my.prayers.times
twitter_username                          : My_Prayers_App
github_username                           : my-prayers
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Accurate Prayer Times
    description                           : Get precise prayer times based on your location and multiple calculation conventions.
    fontawesome_icon_name                 : clock
    
  - title                                 : Azkars
    description                           : Access 287 authentic daily Azkars from Hisnul Muslim with sharing and reminder options.
    fontawesome_icon_name                 : praying-hands

  - title                                 : Qibla Direction
    description                           : Find the accurate Qibla direction using a built-in compass, wherever you are.
    fontawesome_icon_name                 : compass

  - title                                 : Offline Location Finder
    description                           : Manually find your location without internet using GPS or search to get prayer times.
    fontawesome_icon_name                 : map-marker-alt

  - title                                 : 99 Names of Allah
    description                           : Explore and reflect on the 99 beautiful Names of Allah with meanings.
    fontawesome_icon_name                 : quran
  
  - title                                 : Notifications & Reminders
    description                           : Customize Adhan alerts, tones, silent mode, and reminders for every prayer and daily Azkars.
    fontawesome_icon_name                 : bell



# Theme Settings
topbar_color                              : "#47A34B"
topbar_transparency                       : 0.9
topbar_title_color                        : "#ffffff"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#C5EDBD"
cover_overlay_transparency                : 1

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#47A34B"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#47A34B"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
